In [1]:
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pprint
import pyspark
import pyspark.sql.functions as F
import utils
from pyspark.sql.functions import col
from pyspark.sql.types import StringType, IntegerType, FloatType, DateType

import utils.data_processing_bronze_table
import utils.data_processing_attribute_silver_table
import utils.data_processing_financials_silver_table
import utils.data_processing_clickstream_silver_table
import utils.data_processing_lms_silver_table
import utils.data_processing_lms_gold_table

In [2]:
# Initialize SparkSession
spark = (
    pyspark.sql.SparkSession.builder
.appName("dev")
.master("local[*]")
.getOrCreate()
)

# Set log level to ERROR to hide warnings
spark.sparkContext.setLogLevel("ERROR")

# star is to use all available resources on the local machine. You can also specify a number, e.g., "local[4]" to use 4 cores.

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/10/10 07:32:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
gold_label_store_directory = "datamart/gold/label_store/"

if not os.path.exists(gold_label_store_directory):
    os.makedirs(gold_label_store_directory)

In [4]:
snapshot_date_str = "2023-01-01"

start_date_str = "2023-01-01"
end_date_str = "2024-12-01"

def generate_first_of_month_dates(start_date_str, end_date_str):
    # Convert the date strings to datetime objects
    start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
    end_date = datetime.strptime(end_date_str, "%Y-%m-%d")
    
    # List to store the first of month dates
    first_of_month_dates = []

    # Start from the first of the month of the start_date
    current_date = datetime(start_date.year, start_date.month, 1)

    while current_date <= end_date:
        # Append the date in yyyy-mm-dd format
        first_of_month_dates.append(current_date.strftime("%Y-%m-%d"))
        
        # Move to the first of the next month
        if current_date.month == 12:
            current_date = datetime(current_date.year + 1, 1, 1)
        else:
            current_date = datetime(current_date.year, current_date.month + 1, 1)

    return first_of_month_dates

dates_str_lst = generate_first_of_month_dates(start_date_str, end_date_str)
dates_str_lst

['2023-01-01',
 '2023-02-01',
 '2023-03-01',
 '2023-04-01',
 '2023-05-01',
 '2023-06-01',
 '2023-07-01',
 '2023-08-01',
 '2023-09-01',
 '2023-10-01',
 '2023-11-01',
 '2023-12-01',
 '2024-01-01',
 '2024-02-01',
 '2024-03-01',
 '2024-04-01',
 '2024-05-01',
 '2024-06-01',
 '2024-07-01',
 '2024-08-01',
 '2024-09-01',
 '2024-10-01',
 '2024-11-01',
 '2024-12-01']

In [7]:
silver_loan_daily_directory = "datamart/silver/lms_loan_daily/"
for date_str in dates_str_lst:
    utils.data_processing_lms_gold_table.process_labels_gold_table(date_str, silver_loan_daily_directory, gold_label_store_directory, spark, dpd = 30, mob = 6)

loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_01_01.parquet row count: 530

saved to: datamart/gold/label_store/gold_label_store_2023_01_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_02_01.parquet row count: 1031

saved to: datamart/gold/label_store/gold_label_store_2023_02_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_03_01.parquet row count: 1537
saved to: datamart/gold/label_store/gold_label_store_2023_03_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_04_01.parquet row count: 2047

saved to: datamart/gold/label_store/gold_label_store_2023_04_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_05_01.parquet row count: 2568

saved to: datamart/gold/label_store/gold_label_store_2023_05_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_06_01.parquet row count: 3085

saved to: datamart/gold/label_store/gold_label_store_2023_06_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_07_01.parquet row count: 3556

saved to: datamart/gold/label_store/gold_label_store_2023_07_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_08_01.parquet row count: 4037

saved to: datamart/gold/label_store/gold_label_store_2023_08_01.parquet

loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_09_01.parquet row count: 4491

saved to: datamart/gold/label_store/gold_label_store_2023_09_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_10_01.parquet row count: 4978

saved to: datamart/gold/label_store/gold_label_store_2023_10_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_11_01.parquet row count: 5469
saved to: datamart/gold/label_store/gold_label_store_2023_11_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2023_12_01.parquet row count: 5428

saved to: datamart/gold/label_store/gold_label_store_2023_12_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_01_01.parquet row count: 5412

saved to: datamart/gold/label_store/gold_label_store_2024_01_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_02_01.parquet row count: 5424
saved to: datamart/gold/label_store/gold_label_store_2024_02_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_03_01.parquet row count: 5425
saved to: datamart/gold/label_store/gold_label_store_2024_03_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_04_01.parquet row count: 5417
saved to: datamart/gold/label_store/gold_label_store_2024_04_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_05_01.parquet row count: 5391

saved to: datamart/gold/label_store/gold_label_store_2024_05_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_06_01.parquet row count: 5418

saved to: datamart/gold/label_store/gold_label_store_2024_06_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_07_01.parquet row count: 5442

saved to: datamart/gold/label_store/gold_label_store_2024_07_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_08_01.parquet row count: 5531
saved to: datamart/gold/label_store/gold_label_store_2024_08_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_09_01.parquet row count: 5537

saved to: datamart/gold/label_store/gold_label_store_2024_09_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_10_01.parquet row count: 5502
saved to: datamart/gold/label_store/gold_label_store_2024_10_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_11_01.parquet row count: 5501

saved to: datamart/gold/label_store/gold_label_store_2024_11_01.parquet
loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_2024_12_01.parquet row count: 5531

saved to: datamart/gold/label_store/gold_label_store_2024_12_01.parquet

In [5]:
gold_label_store_directory = "datamart/gold/label_store/"
silver_loan_daily_directory = "datamart/silver/lms_loan_daily/"
# gold_label_main = utils.data_processing_lms_gold_table.process_labels_gold_table_main(silver_loan_daily_directory,gold_label_store_directory,spark,dpd = 30, mob = 6)

loaded from: datamart/silver/lms_loan_daily/silver_loan_daily_main_.parquet row count: 137500

saved to: datamart/gold/label_store/gold_label_store_main_.parquet

In [3]:
## setting up file directory config:
bronze_directory = "datamart/bronze/"

attribute_filename = "features_attributes/features_attributes_main.csv"
financial_filename = "features_financials/features_financials_main.csv"
loan_filename = "lms_loan_daily/lms_loan_daily_main.csv"
clickstream_filename = "feature_clickstream/feature_clickstream_main.csv"

silver_attributes_daily_directory = "datamart/silver/features_attributes/"
silver_financials_daily_directory = "datamart/silver/features_financials/"
silver_loan_daily_directory = "datamart/silver/lms_loan_daily/"
silver_clickstream_directory ="datamart/silver/feature_clickstream/"

silver_attribute_filename = "features_attributes/silver_features_attributes_main.parquet"
silver_financial_filename = "features_financials/silver_features_financials_main.parquet"
gold_loan_filename = "datamart/gold/label_store/gold_label_store_main_.parquet"
silver_clickstream_filename = "feature_clickstream/silver_clickstream_main_.parquet"


silver_directory = "datamart/silver/"
os.makedirs(silver_directory, exist_ok = True)

gold_directory = "datamart/gold/"
os.makedirs(gold_directory, exist_ok = True)

silver_merged_processed_directory = "datamart/silver/merged/"
os.makedirs(silver_merged_processed_directory, exist_ok = True)

gold_features_main_directory = "datamart/gold/feature_store/"
os.makedirs(gold_features_main_directory, exist_ok = True)


os.makedirs(bronze_directory, exist_ok = True)
os.makedirs(silver_attributes_daily_directory, exist_ok = True)
os.makedirs(silver_financials_daily_directory, exist_ok = True)
os.makedirs(silver_loan_daily_directory, exist_ok = True)
os.makedirs(silver_clickstream_directory, exist_ok = True)

data_start_date_str = "2023-01-01"
data_end_date_str = "2024-12-01"

train_end_date = '2024-09-01'
unseen_start_date = '2024-10-01'

In [4]:
utils.data_processing_lms_gold_table.process_features_gold_table_main(silver_directory, spark, 
                            silver_attribute_filename, silver_financial_filename, gold_loan_filename, silver_clickstream_filename,gold_features_main_directory,
                            train_end_date, unseen_start_date,data_start_date_str,data_end_date_str,
                            model_train_date_str="2025-06-01", validation_period_months=1,
                            test_period_months=2, oot_period_months=2)

loaded from: datamart/silver/features_attributes/silver_features_attributes_main.parquet row count: 12500
loaded from: datamart/silver/features_financials/silver_features_financials_main.parquet row count: 12500
loaded from: datamart/gold/label_store/gold_label_store_main_.parquet row count: 12500
loaded from: datamart/silver/feature_clickstream/silver_clickstream_main_.parquet row count: 215376

Date split boundaries:
Train: 2023-01-01 to 2024-12-31
Validation: 2025-01-01 to 2025-01-31
Test: 2025-02-01 to 2025-03-31
OOT: 2025-04-01 to 2025-05-31

Train: 8974 rows
+-----+-----+-------------------+
|label|count|         proportion|
+-----+-----+-------------------+
|    0| 6383| 0.7112770225094718|
|    1| 2591|0.28872297749052817|
+-----+-----+-------------------+

+----------+----------+
|  min_date|  max_date|
+----------+----------+
|2023-07-01|2024-12-01|
+----------+----------+


Validation: 505 rows
+-----+-----+------------------+
|label|count|        proportion|
+-----+-----+------------------+
|    0|  350| 0.693069306930693|
|    1|  155|0.3069306930693069|
+-----+-----+------------------+

+----------+----------+
|  min_date|  max_date|
+----------+----------+
|2025-01-01|2025-01-01|
+----------+----------+


Test: 1036 rows
+-----+-----+-------------------+
|label|count|         proportion|
+-----+-----+-------------------+
|    0|  710| 0.6853281853281853|
|    1|  326|0.31467181467181465|
+-----+-----+-------------------+

+----------+----------+
|  min_date|  max_date|
+----------+----------+
|2025-02-01|2025-03-01|
+----------+----------+


OOT: 944 rows
+-----+-----+-----------------+
|label|count|       proportion|
+-----+-----+-----------------+
|    0|  695|0.736228813559322|
|    1|  249|0.263771186440678|
+-----+-----+-----------------+

+----------+----------+
|  min_date|  max_date|
+----------+----------+
|2025-04-01|2025-05-01|
+----------+----------+

Changed Credit Limit group medians:
+-----------+---------------------+---------------------------+
|Credit_Mix |Payment_of_Min_Amount|Changed_Credit_Limit_Median|
+-----------+---------------------+---------------------------+
|Bad        |NM                   |15.48                      |
|Bad        |Yes                  |14.05                      |
|Good       |NM                   |6.13                       |
|Good       |No                   |5.97                       |
|Not Defined|NM                   |9.23                       |
|Not Defined|No                   |6.03                       |
|Not Defined|Yes                  |12.64                      |
|Standard   |NM                   |11.29                      |
|Standard   |No                   |6.71                       |
|Standard   |Yes                  |12.62                      |
+-----------+---------------------+---------------------------+

Remaining missing Changed_Credit_Limit - Train: 0
Remaining missing Changed_Credit_Limit - Validation: 0
Remaining missing Changed_Credit_Limit - Test: 0
Remaining missing Changed_Credit_Limit - OOT: 0
Initial Age edges:
[18.0, 26.0, 34.0, 42.0, 56.0]
Age income lookup:

+------------+-------+------------------+----------+-----+
|  Occupation|Age_Bin| log_income_median|age_median|count|
+------------+-------+------------------+----------+-----+
|MediaManager|  35-42|10.482973805102581|        38|  134|
|  Accountant|  27-34|10.487246912994182|        30|  123|
|  Accountant|  18-26|10.534979551138033|        23|  124|
|     Teacher|  27-34|10.431097466232934|        31|  121|
|    Engineer|  27-34|10.547302713164944|        31|  133|
|   Scientist|  43-56|10.649030090887043|        47|  134|
|Entrepreneur|  18-26|10.461044078789724|        22|  128|
|            |  27-34|10.473715360069058|        31|  157|
|  Journalist|  35-42|10.353238088050679|        38|  128|
|MediaManager|  43-56|10.566129616052383|        48|  134|
|    Mechanic|  43-56|10.787507917792388|        48|  127|
|  Journalist|  27-34|10.521021256243461|        31|  121|
|      Doctor|  18-26|10.545569311592208|        22|  141|
|            |  18-26|10.518878618160022|        22|  135|
|      Writer|  43-56|10.640929596470285|        47|  121|
|    Musician|  35-42|10.644853305366548|        38|  124|
|      Writer|  27-34|10.479185931128168|        30|  118|
|     Manager|  27-34|10.526831753984638|        31|  116|
|      Lawyer|  35-42|10.474983054447412|        39|  143|
|MediaManager|  27-34|10.499869442396825|        30|  121|
+------------+-------+------------------+----------+-----+
only showing top 20 rows

Overall median age: 34
Final Age edges:
[18.0, 30.0, 35.0, 44.0, 56.0]
Final Age labels:
['18-30', '31-35', '36-44', '45-56']
TRAIN
======
Total rows: 8974
+---------------------+-----+
|Age_imputation_method|count|
+---------------------+-----+
| occupation_income...|  813|
|    occupation_median|  753|
|             original| 7408|
+---------------------+-----+

+-------+-----+
|Age_Bin|count|
+-------+-----+
|  18-30| 2500|
|  31-35| 2107|
|  36-44| 2366|
|  45-56| 2001|
+-------+-----+

UNSEEN
=======
Total rows: 944
+---------------------+-----+
|Age_imputation_method|count|
+---------------------+-----+
| occupation_income...|   87|
|    occupation_median|   77|
|             original|  780|
+---------------------+-----+

+-------+-----+
|Age_Bin|count|
+-------+-----+
|  18-30|  265|
|  31-35|  203|
|  36-44|  282|
|  45-56|  194|
+-------+-----+

+-----------+---+------------------------+---------+-----------+-------+---------------+------------------------+-------------------------+
|Customer_ID|Age|Credit_History_Age_Years|Age_clean|Age_imputed|Age_Bin|Age_was_invalid|Age_History_Inconsistent|Age_imputation_method    |
+-----------+---+------------------------+---------+-----------+-------+---------------+------------------------+-------------------------+
|CUS_0x5097 |20 |22.833333333333332      |NULL     |47         |45-56  |1              |1                       |occupation_income_age_bin|
|CUS_0x50a2 |36 |30.333333333333332      |36       |36         |36-44  |0              |0                       |original                 |
|CUS_0x5a03 |16 |10.333333333333334      |NULL     |47         |45-56  |1              |0                       |occupation_income_age_bin|
|CUS_0x6387 |27 |26.833333333333332      |27       |27         |18-30  |0              |0                       |original                 |
|CUS_0x720a |27 |14.5                    |27       |27         |18-30  |0              |0                       |original                 |
|CUS_0x727e |44 |33.416666666666664      |44       |44         |36-44  |0              |0                       |original                 |
|CUS_0x74e8 |39 |25.416666666666668      |39       |39         |36-44  |0              |0                       |original                 |
|CUS_0x780c |26 |14.666666666666666      |26       |26         |18-30  |0              |0                       |original                 |
|CUS_0x79bc |14 |10.333333333333334      |NULL     |31         |31-35  |1              |0                       |occupation_income_age_bin|
|CUS_0x7d25 |22 |17.5                    |22       |22         |18-30  |0              |0                       |original                 |
|CUS_0x7de5 |48 |16.916666666666668      |48       |48         |45-56  |0              |0                       |original                 |
|CUS_0x827f |20 |22.666666666666668      |NULL     |31         |31-35  |1              |1                       |occupation_income_age_bin|
|CUS_0x839e |23 |31.0                    |NULL     |22         |18-30  |1              |1                       |occupation_income_age_bin|
|CUS_0x843  |33 |7.0                     |33       |33         |31-35  |0              |0                       |original                 |
|CUS_0x8c1d |27 |19.75                   |27       |27         |18-30  |0              |0                       |original                 |
|CUS_0x516c |47 |24.666666666666668      |47       |47         |45-56  |0              |0                       |original                 |
|CUS_0x53f6 |26 |20.916666666666668      |26       |26         |18-30  |0              |0                       |original                 |
|CUS_0x5899 |29 |15.666666666666666      |29       |29         |18-30  |0              |0                       |original                 |
|CUS_0x5b7  |44 |13.75                   |44       |44         |36-44  |0              |0                       |original                 |
|CUS_0x5bcb |33 |19.166666666666668      |33       |33         |31-35  |0              |0                       |original                 |
+-----------+---+------------------------+---------+-----------+-------+---------------+------------------------+-------------------------+
only showing top 20 rows

+-----------+---+------------------------+---------+-----------+-------+---------------+------------------------+---------------------+
|Customer_ID|Age|Credit_History_Age_Years|Age_clean|Age_imputed|Age_Bin|Age_was_invalid|Age_History_Inconsistent|Age_imputation_method|
+-----------+---+------------------------+---------+-----------+-------+---------------+------------------------+---------------------+
|CUS_0x5548 |27 |16.333333333333332      |27       |27         |18-30  |0              |0                       |original             |
|CUS_0x559e |29 |8.916666666666666       |29       |29         |18-30  |0              |0                       |original             |
|CUS_0x5d7e |16 |12.25                   |NULL     |35         |31-35  |1              |0                       |occupation_median    |
|CUS_0x7443 |20 |18.166666666666668      |20       |20         |18-30  |0              |0                       |original             |
|CUS_0x79ef |38 |17.0                    |38       |38         |36-44  |0              |0                       |original             |
|CUS_0x85b2 |38 |30.0                    |38       |38         |36-44  |0              |0                       |original             |
|CUS_0x892d |16 |8.25                    |NULL     |33         |31-35  |1              |0                       |occupation_median    |
|CUS_0x7e94 |32 |16.0                    |32       |32         |31-35  |0              |0                       |original             |
|CUS_0x8697 |23 |11.25                   |23       |23         |18-30  |0              |0                       |original             |
|CUS_0x53cb |33 |14.333333333333334      |33       |33         |31-35  |0              |0                       |original             |
|CUS_0x5b02 |50 |27.25                   |50       |50         |45-56  |0              |0                       |original             |
|CUS_0x899  |18 |9.75                    |18       |18         |18-30  |0              |0                       |original             |
|CUS_0x504f |31 |17.833333333333332      |31       |31         |31-35  |0              |0                       |original             |
|CUS_0x8688 |47 |26.833333333333332      |47       |47         |45-56  |0              |0                       |original             |
|CUS_0x87df |29 |12.333333333333334      |29       |29         |18-30  |0              |0                       |original             |
|CUS_0x669c |19 |16.833333333333332      |19       |19         |18-30  |0              |0                       |original             |
|CUS_0x669f |42 |13.75                   |42       |42         |36-44  |0              |0                       |original             |
|CUS_0x6ec7 |41 |19.166666666666668      |41       |41         |36-44  |0              |0                       |original             |
|CUS_0x70a0 |46 |2.0                     |46       |46         |45-56  |0              |0                       |original             |
|CUS_0x89b2 |41 |33.5                    |41       |41         |36-44  |0              |0                       |original             |
+-----------+---+------------------------+---------+-----------+-------+---------------+------------------------+---------------------+
only showing top 20 rows

Num_Bank_Accounts P95: 10.0
Null records for Num_Bank_Accounts: 0
Num_Credit_Card P95: 10.0
Null records for Num_Credit_Card: 0

+-----------+-----------------+-------------------+---------------------+-------------------------+-------------------------+-------------------------------+---------------+------------------+--------------------+------------------------+------------------------+------------------------------+
|Customer_ID|Num_Bank_Accounts|Bank_Accounts_clean|Bank_Accounts_imputed|Bank_Accounts_Imputed_Bin|Bank_Accounts_Was_Invalid|Bank_Accounts_imputation_method|Num_Credit_Card|Credit_Cards_clean|Credit_Cards_imputed|Credit_Cards_Imputed_Bin|Credit_Cards_Was_Invalid|Credit_Cards_imputation_method|
+-----------+-----------------+-------------------+---------------------+-------------------------+-------------------------+-------------------------------+---------------+------------------+--------------------+------------------------+------------------------+------------------------------+
|CUS_0x69cd |5                |5                  |5                    |4-5                      |0                        |original                       |6              |6                 |6                   |6-7                     |0                       |original                      |
|CUS_0x60f5 |10               |10                 |10                   |8-10                     |0                        |original                       |5              |5                 |5                   |5-5                     |0                       |original                      |
|CUS_0x5413 |4                |4                  |4                    |4-5                      |0                        |original                       |4              |4                 |4                   |0-4                     |0                       |original                      |
|CUS_0x7e12 |4                |4                  |4                    |4-5                      |0                        |original                       |5              |5                 |5                   |5-5                     |0                       |original                      |
|CUS_0x8336 |7                |7                  |7                    |6-7                      |0                        |original                       |6              |6                 |6                   |6-7                     |0                       |original                      |
|CUS_0x6ecf |6                |6                  |6                    |6-7                      |0                        |original                       |3              |3                 |3                   |0-4                     |0                       |original                      |
|CUS_0x5bfc |8                |8                  |8                    |8-10                     |0                        |original                       |10             |10                |10                  |8-10                    |0                       |original                      |
|CUS_0x82fd |8                |8                  |8                    |8-10                     |0                        |original                       |7              |7                 |7                   |6-7                     |0                       |original                      |
|CUS_0x5898 |7                |7                  |7                    |6-7                      |0                        |original                       |5              |5                 |5                   |5-5                     |0                       |original                      |
|CUS_0x6569 |3                |3                  |3                    |0-3                      |0                        |original                       |3              |3                 |3                   |0-4                     |0                       |original                      |
|CUS_0x7edc |5                |5                  |5                    |4-5                      |0                        |original                       |3              |3                 |3                   |0-4                     |0                       |original                      |
|CUS_0x5275 |6                |6                  |6                    |6-7                      |0                        |original                       |7              |7                 |7                   |6-7                     |0                       |original                      |
|CUS_0x5984 |6                |6                  |6                    |6-7                      |0                        |original                       |9              |9                 |9                   |8-10                    |0                       |original                      |
|CUS_0x65b9 |4                |4                  |4                    |4-5                      |0                        |original                       |563            |NULL              |6                   |6-7                     |1                       |occupation_age_bin_median     |
|CUS_0x7af8 |8                |8                  |8                    |8-10                     |0                        |original                       |10             |10                |10                  |8-10                    |0                       |original                      |
|CUS_0x8bfe |5                |5                  |5                    |4-5                      |0                        |original                       |5              |5                 |5                   |5-5                     |0                       |original                      |
|CUS_0x8067 |5                |5                  |5                    |4-5                      |0                        |original                       |5              |5                 |5                   |5-5                     |0                       |original                      |
|CUS_0x5a59 |6                |6                  |6                    |6-7                      |0                        |original                       |8              |8                 |8                   |8-10                    |0                       |original                      |
|CUS_0x77ec |10               |10                 |10                   |8-10                     |0                        |original                       |7              |7                 |7                   |6-7                     |0                       |original                      |
|CUS_0x6831 |8                |8                  |8                    |8-10                     |0                        |original                       |7              |7                 |7                   |6-7                     |0                       |original                      |
+-----------+-----------------+-------------------+---------------------+-------------------------+-------------------------+-------------------------------+---------------+------------------+--------------------+------------------------+------------------------+------------------------------+
only showing top 20 rows

+-----------+-----------------+-------------------+---------------------+-------------------------+-------------------------+-------------------------------+---------------+------------------+--------------------+------------------------+------------------------+------------------------------+
|Customer_ID|Num_Bank_Accounts|Bank_Accounts_clean|Bank_Accounts_imputed|Bank_Accounts_Imputed_Bin|Bank_Accounts_Was_Invalid|Bank_Accounts_imputation_method|Num_Credit_Card|Credit_Cards_clean|Credit_Cards_imputed|Credit_Cards_Imputed_Bin|Credit_Cards_Was_Invalid|Credit_Cards_imputation_method|
+-----------+-----------------+-------------------+---------------------+-------------------------+-------------------------+-------------------------------+---------------+------------------+--------------------+------------------------+------------------------+------------------------------+
|CUS_0x559e |1665             |NULL               |6                    |6-7                      |1                        |occupation_age_bin_median      |5              |5                 |5                   |5-5                     |0                       |original                      |
|CUS_0x79ef |9                |9                  |9                    |8-10                     |0                        |original                       |8              |8                 |8                   |8-10                    |0                       |original                      |
|CUS_0x6df3 |8                |8                  |8                    |8-10                     |0                        |original                       |3              |3                 |3                   |0-4                     |0                       |original                      |
|CUS_0x628d |7                |7                  |7                    |6-7                      |0                        |original                       |6              |6                 |6                   |6-7                     |0                       |original                      |
|CUS_0x505f |8                |8                  |8                    |8-10                     |0                        |original                       |6              |6                 |6                   |6-7                     |0                       |original                      |
|CUS_0x8c6f |9                |9                  |9                    |8-10                     |0                        |original                       |5              |5                 |5                   |5-5                     |0                       |original                      |
|CUS_0x523e |7                |7                  |7                    |6-7                      |0                        |original                       |3              |3                 |3                   |0-4                     |0                       |original                      |
|CUS_0x704  |5                |5                  |5                    |4-5                      |0                        |original                       |5              |5                 |5                   |5-5                     |0                       |original                      |
|CUS_0x6c6d |7                |7                  |7                    |6-7                      |0                        |original                       |6              |6                 |6                   |6-7                     |0                       |original                      |
|CUS_0x6c23 |7                |7                  |7                    |6-7                      |0                        |original                       |3              |3                 |3                   |0-4                     |0                       |original                      |
|CUS_0x660c |10               |10                 |10                   |8-10                     |0                        |original                       |8              |8                 |8                   |8-10                    |0                       |original                      |
|CUS_0x62d7 |7                |7                  |7                    |6-7                      |0                        |original                       |6              |6                 |6                   |6-7                     |0                       |original                      |
|CUS_0x111b |3                |3                  |3                    |0-3                      |0                        |original                       |6              |6                 |6                   |6-7                     |0                       |original                      |
|CUS_0x2696 |10               |10                 |10                   |8-10                     |0                        |original                       |8              |8                 |8                   |8-10                    |0                       |original                      |
|CUS_0x1820 |6                |6                  |6                    |6-7                      |0                        |original                       |5              |5                 |5                   |5-5                     |0                       |original                      |
|CUS_0x4dac |7                |7                  |7                    |6-7                      |0                        |original                       |6              |6                 |6                   |6-7                     |0                       |original                      |
|CUS_0x1929 |8                |8                  |8                    |8-10                     |0                        |original                       |7              |7                 |7                   |6-7                     |0                       |original                      |
|CUS_0x219a |9                |9                  |9                    |8-10                     |0                        |original                       |6              |6                 |6                   |6-7                     |0                       |original                      |
|CUS_0x1ce1 |4                |4                  |4                    |4-5                      |0                        |original                       |4              |4                 |4                   |0-4                     |0                       |original                      |
|CUS_0x488b |6                |6                  |6                    |6-7                      |0                        |original                       |10             |10                |10                  |8-10                    |0                       |original                      |
+-----------+-----------------+-------------------+---------------------+-------------------------+-------------------------+-------------------------------+---------------+------------------+--------------------+------------------------+------------------------+------------------------------+
only showing top 20 rows

Length of temp after LEFT join: 215376

Length of filtered temp (days_before > 0): 129778

Feature rows after clickstream enrichment: 11459
Clickstream columns joined to gold table: ['labels_snapshot_date', 'fe_10_mean_90d', 'fe_5_mean_90d', 'fe_4_mean_90d', 'fe_9_mean_90d', 'fe_3_std_60d', 'fe_8_mean_90d', 'fe_3_mean_90d', 'fe_14_trend_30d', 'fe_1_trend_30d', 'fe_16_std_60d']

+-----------+--------------------+--------------------+--------------+-------------+------------------+------------------+------------+------------------+------------------+---------------+--------------+-------------+
|Customer_ID|labels_snapshot_date|labels_snapshot_date|fe_10_mean_90d|fe_5_mean_90d|fe_4_mean_90d     |fe_9_mean_90d     |fe_3_std_60d|fe_8_mean_90d     |fe_3_mean_90d     |fe_14_trend_30d|fe_1_trend_30d|fe_16_std_60d|
+-----------+--------------------+--------------------+--------------+-------------+------------------+------------------+------------+------------------+------------------+---------------+--------------+-------------+
|CUS_0x5035 |2024-06-01          |2024-06-01          |229.0         |42.0         |153.5             |130.0             |NULL        |121.0             |85.5              |NULL           |NULL          |NULL         |
|CUS_0x5036 |2023-10-01          |2023-10-01          |77.0          |131.5        |-62.5             |191.0             |NULL        |186.0             |163.0             |NULL           |NULL          |NULL         |
|CUS_0x502c |2023-11-01          |2023-11-01          |51.0          |63.5         |80.5              |104.5             |NULL        |147.5             |103.5             |NULL           |NULL          |NULL         |
|CUS_0x5046 |2024-01-01          |2024-01-01          |86.5          |71.5         |127.5             |42.0              |NULL        |89.5              |58.5              |NULL           |NULL          |NULL         |
|CUS_0x501c |2024-09-01          |2024-09-01          |235.5         |164.5        |235.5             |149.0             |NULL        |19.0              |169.5             |NULL           |NULL          |NULL         |
|CUS_0x5002 |2023-10-01          |2023-10-01          |78.0          |59.5         |184.5             |193.0             |NULL        |18.5              |150.0             |NULL           |NULL          |NULL         |
|CUS_0x5044 |2024-07-01          |2024-07-01          |95.5          |142.5        |153.5             |41.0              |NULL        |-3.0              |57.0              |NULL           |NULL          |NULL         |
|CUS_0x5029 |2023-12-01          |2023-12-01          |157.0         |68.5         |93.0              |42.0              |NULL        |132.0             |179.0             |NULL           |NULL          |NULL         |
|CUS_0x5012 |2024-05-01          |2024-05-01          |-33.0         |134.0        |145.33333333333334|116.33333333333333|NULL        |115.66666666666667|63.666666666666664|NULL           |NULL          |NULL         |
|CUS_0x5048 |2024-09-01          |2024-09-01          |82.5          |136.5        |196.0             |44.5              |NULL        |163.5             |77.5              |NULL           |NULL          |NULL         |
+-----------+--------------------+--------------------+--------------+-------------+------------------+------------------+------------+------------------+------------------+---------------+--------------+-------------+
only showing top 10 rows

saved to: datamart/gold/feature_store/gold_feature_store_main_cs.parquet

In [5]:
fs_sdf_cs = spark.read.option("header", "true").parquet('datamart/gold/feature_store/gold_feature_store_main_cs.parquet')
fs_sdf_cs = fs_sdf_cs.toPandas()
display(fs_sdf_cs.head())
display(fs_sdf_cs.info())
print("number of customers:", fs_sdf_cs['Customer_ID'].nunique())

,Customer_ID,labels_snapshot_date,Occupation,Age_Bin,loan_id,Age,attributes_snapshot_date,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,fe_10_mean_90d,fe_5_mean_90d,fe_4_mean_90d,fe_9_mean_90d,fe_3_std_60d,fe_8_mean_90d,fe_3_mean_90d,fe_14_trend_30d,fe_1_trend_30d,fe_16_std_60d
0,CUS_0x2174,2023-08-01,Manager,36-44,CUS_0x2174_2023_02_01,36,2023-02-01,94934.937500,8039.245117,2,...,170.500000,66.0,-55.500000,3.000000,NaN,141.500000,188.5,NaN,NaN,NaN
1,CUS_0x78eb,2024-05-01,Musician,36-44,CUS_0x78eb_2023_11_01,38,2023-11-01,131121.750000,11211.812500,4,...,176.666667,168.0,47.333333,112.333333,NaN,147.666667,162.0,NaN,NaN,NaN
2,CUS_0x8bcc,2023-11-01,,45-56,CUS_0x8bcc_2023_05_01,51,2023-05-01,123485.039062,10299.419922,4,...,106.500000,42.5,171.000000,121.000000,NaN,-32.000000,-73.5,NaN,NaN,NaN
3,CUS_0x6f40,2024-04-01,Musician,31-35,CUS_0x6f40_2023_10_01,31,2023-10-01,82995.820312,7092.318359,2,...,37.000000,8.5,4.000000,145.500000,12.727922,-9.500000,157.0,NaN,NaN,65.053824
4,CUS_0x19a7,2024-07-01,Musician,31-35,CUS_0x19a7_2024_01_01,34,2024-01-01,62348.460938,4942.705078,4,...,154.000000,140.0,120.000000,108.500000,NaN,255.000000,167.0,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11459 entries, 0 to 11458
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Customer_ID                   11459 non-null  object
 1   labels_snapshot_date          11459 non-null  object
 2   Occupation                    11459 non-null  object
 3   Age_Bin                       11459 non-null  object
 4   loan_id                       11459 non-null  object
 5   Age                           11459 non-null  int32
 6   attributes_snapshot_date      11459 non-null  object
 7   Annual_Income                 11459 non-null  float32
 8   Monthly_Inhand_Salary         11459 non-null  float32
 9   Num_Bank_Accounts             11459 non-null  int32
 10  Num_Credit_Card               11459 non-null  int32
 11  Interest_Rate                 11459 non-null  int32
 12  Delay_from_due_date           11459 non-null  int32
 13  Num_of_Delayed_Payment        11459 non-null  int32
 14  Changed_Credit_Limit          11459 non-null  float32
 15  Num_Credit_Inquiries          11459 non-null  int32
 16  Outstanding_Debt              11459 non-null  float32
 17  Credit_Utilization_Ratio      11459 non-null  float32
 18  Total_EMI_per_month           11459 non-null  float32
 19  Amount_invested_monthly       11459 non-null  float32
 20  Monthly_Balance               11459 non-null  float32
 21  financials_snapshot_date      11459 non-null  object
 22  Num_of_Loan_Cleaned           11459 non-null  int32
 23  Loan_Home_Equity_Loan         11459 non-null  int32
 24  Loan_Payday_Loan              11459 non-null  int32
 25  Loan_Personal_Loan            11459 non-null  int32
 26  Loan_Debt_Consolidation_Loan  11459 non-null  int32
 27  Loan_Mortgage_Loan            11459 non-null  int32
 28  Loan_Student_Loan             11459 non-null  int32
 29  Loan_Credit_Builder_Loan      11459 non-null  int32
 30  Loan_Auto_Loan                11459 non-null  int32
 31  Loan_Not_Specified            11459 non-null  int32
 32  Credit_Mix_Not_Defined        11459 non-null  int32
 33  Credit_Mix_Good               11459 non-null  int32
 34  Credit_Mix_Bad                11459 non-null  int32
 35  Credit_Mix_Standard           11459 non-null  int32
 36  Payment_of_Min_Amount_NM      11459 non-null  int32
 37  Payment_of_Min_Amount_No      11459 non-null  int32
 38  Payment_of_Min_Amount_Yes     11459 non-null  int32
 39  Credit_History_Age_Years      11459 non-null  float64
 40  Payment_Behaviour_Imputed     11459 non-null  object
 41  Age_imputed                   11459 non-null  int32
 42  Bank_Accounts_imputed         11459 non-null  int32
 43  Credit_Cards_imputed          11459 non-null  int32
 44  Bank_Accounts_Imputed_Bin     11459 non-null  object
 45  Credit_Cards_Imputed_Bin      11459 non-null  object
 46  Num_Fin_Pdts                  11459 non-null  int32
 47  Debt_per_Credit_Account       11020 non-null  float64
 48  Delayed_Payments_per_Card     11175 non-null  float64
 49  InterestRate_x_Debt           11459 non-null  float32
 50  data_split                    11459 non-null  object
 51  fe_10_mean_90d                8974 non-null   float64
 52  fe_5_mean_90d                 8974 non-null   float64
 53  fe_4_mean_90d                 8974 non-null   float64
 54  fe_9_mean_90d                 8974 non-null   float64
 55  fe_3_std_60d                  941 non-null    float64
 56  fe_8_mean_90d                 8974 non-null   float64
 57  fe_3_mean_90d                 8974 non-null   float64
 58  fe_14_trend_30d               454 non-null    float64
 59  fe_1_trend_30d                454 non-null    float64
 60  fe_16_std_60d                 941 non-null    float64
dtypes: float32(9), float64(13), int32(28), object(11)
memory usage: 3.7+ MB

None

number of customers: 11459

In [21]:
fs_sdf = spark.read.option("header", "true").parquet('datamart/gold/feature_store/gold_feature_store_main_.parquet')
fs_sdf = fs_sdf.toPandas()
display(fs_sdf.head())
display(fs_pdf.info())
print("number of customers:", fs_pdf['Customer_ID'].nunique())

,Occupation,Age_Bin,Customer_ID,loan_id,labels_snapshot_date,Age,attributes_snapshot_date,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,fe_20,clicks_snapshot_date,Age_imputed,Bank_Accounts_imputed,Credit_Cards_imputed,Bank_Accounts_Imputed_Bin,Credit_Cards_Imputed_Bin,Debt_per_Credit_Account,Delayed_Payments_per_Card,InterestRate_x_Debt
0,Developer,37-43,CUS_0x7409,CUS_0x7409_2023_11_01,2024-05-01,38,2023-11-01,29510.869141,2560.239258,4,...,74.0,2024-05-01,38,4,7,4-5,6-7,104.329090,-0.285714,13771.439453
1,Developer,37-43,CUS_0x706d,CUS_0x706d_2023_04_01,2023-10-01,39,2023-04-01,62030.640625,4883.220215,3,...,59.0,2023-10-01,39,3,9,0-3,8-10,142.160838,1.666667,42648.250000
2,Developer,37-43,CUS_0x6b44,CUS_0x6b44_2023_12_01,2024-06-01,39,2023-12-01,20742.460938,1801.538330,5,...,-78.0,2024-06-01,39,5,4,4-5,0-4,146.652222,4.500000,10558.959961
3,Developer,37-43,CUS_0x7693,CUS_0x7693_2023_06_01,2023-12-01,40,2023-06-01,52958.429688,4313.202637,8,...,182.0,2023-12-01,40,8,5,8-10,5-5,NaN,NaN,53673.281250
4,Developer,37-43,CUS_0x6dec,CUS_0x6dec_2023_02_01,2023-08-01,42,2023-02-01,16511.394531,1528.949585,2,...,0.0,2023-08-01,42,2,5,0-3,5-5,172.295707,0.000000,9648.559570

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9479 entries, 0 to 9478
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Customer_ID                   9479 non-null   object
 1   labels_snapshot_date          9479 non-null   object
 2   Occupation                    9479 non-null   object
 3   Age_Bin                       9479 non-null   object
 4   loan_id                       9479 non-null   object
 5   Age                           9479 non-null   int32
 6   attributes_snapshot_date      9479 non-null   object
 7   Annual_Income                 9479 non-null   float32
 8   Monthly_Inhand_Salary         9479 non-null   float32
 9   Num_Bank_Accounts             9479 non-null   int32
 10  Num_Credit_Card               9479 non-null   int32
 11  Interest_Rate                 9479 non-null   int32
 12  Delay_from_due_date           9479 non-null   int32
 13  Num_of_Delayed_Payment        9479 non-null   int32
 14  Changed_Credit_Limit          9479 non-null   float32
 15  Num_Credit_Inquiries          9479 non-null   int32
 16  Outstanding_Debt              9479 non-null   float32
 17  Credit_Utilization_Ratio      9479 non-null   float32
 18  Total_EMI_per_month           9479 non-null   float32
 19  Amount_invested_monthly       9479 non-null   float32
 20  Monthly_Balance               9479 non-null   float32
 21  financials_snapshot_date      9479 non-null   object
 22  Num_of_Loan_Cleaned           9479 non-null   int32
 23  Loan_Home_Equity_Loan         9479 non-null   int32
 24  Loan_Payday_Loan              9479 non-null   int32
 25  Loan_Personal_Loan            9479 non-null   int32
 26  Loan_Debt_Consolidation_Loan  9479 non-null   int32
 27  Loan_Mortgage_Loan            9479 non-null   int32
 28  Loan_Student_Loan             9479 non-null   int32
 29  Loan_Credit_Builder_Loan      9479 non-null   int32
 30  Loan_Auto_Loan                9479 non-null   int32
 31  Loan_Not_Specified            9479 non-null   int32
 32  Credit_Mix_Not_Defined        9479 non-null   int32
 33  Credit_Mix_Good               9479 non-null   int32
 34  Credit_Mix_Bad                9479 non-null   int32
 35  Credit_Mix_Standard           9479 non-null   int32
 36  Payment_of_Min_Amount_NM      9479 non-null   int32
 37  Payment_of_Min_Amount_No      9479 non-null   int32
 38  Payment_of_Min_Amount_Yes     9479 non-null   int32
 39  Credit_History_Age_Years      9479 non-null   float64
 40  Payment_Behaviour_Imputed     9479 non-null   object
 41  Age_imputed                   9479 non-null   int32
 42  Bank_Accounts_imputed         9479 non-null   int32
 43  Credit_Cards_imputed          9479 non-null   int32
 44  Bank_Accounts_Imputed_Bin     9479 non-null   object
 45  Credit_Cards_Imputed_Bin      9479 non-null   object
 46  Num_Fin_Pdts                  9479 non-null   int32
 47  Debt_per_Credit_Account       9118 non-null   float64
 48  Delayed_Payments_per_Card     9240 non-null   float64
 49  InterestRate_x_Debt           9479 non-null   float32
 50  data_split                    9479 non-null   object
 51  fe_10_mean_90d                8974 non-null   float64
 52  fe_5_mean_90d                 8974 non-null   float64
 53  fe_4_mean_90d                 8974 non-null   float64
 54  fe_9_mean_90d                 8974 non-null   float64
 55  fe_3_std_60d                  941 non-null    float64
 56  fe_8_mean_90d                 8974 non-null   float64
 57  fe_3_mean_90d                 8974 non-null   float64
 58  fe_14_trend_30d               454 non-null    float64
 59  fe_1_trend_30d                454 non-null    float64
 60  fe_16_std_60d                 941 non-null    float64
dtypes: float32(9), float64(13), int32(28), object(11)
memory usage: 3.1+ MB

None

number of customers: 9479

In [16]:
fs_pdf['Customer_ID'].duplicated().sum()

np.int64(0)